In [109]:
#1: Import libraries
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.mixture import GaussianMixture

#2: Load data & exploratory analysis 
df=pd.read_csv('titanic.csv')
df

,survived,pclass,name,sex,age,fare,sibsp,parch
0,0,3,"Braund, Mr. Owen Harris",male,22.0,NaN,1,0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1,0
2,1,3,"Heikkinen, Miss. Laina",female,26.0,7.9250,0,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1,0
4,0,3,"Allen, Mr. William Henry",male,35.0,8.0500,0,0
...,...,...,...,...,...,...,...,...
709,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,29.1250,0,5
710,0,2,"Montvila, Rev. Juozas",male,27.0,13.0000,0,0
711,1,1,"Graham, Miss. Margaret Edith",female,19.0,30.0000,0,0
712,1,1,"Behr, Mr. Karl Howell",male,26.0,30.0000,0,0
713,0,3,"Dooley, Mr. Patrick",male,32.0,7.7500,0,0

In [110]:
#2: Load data & exploratory analysis 

df.describe()

         survived      pclass         age        fare       sibsp       parch
count  714.000000  714.000000  714.000000  713.000000  714.000000  714.000000
mean     0.406162    2.236695   29.699118   34.733006    0.512605    0.431373
std      0.491460    0.838250   14.526497   52.946076    0.929783    0.853289
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   20.125000    8.050000    0.000000    0.000000
50%      0.000000    2.000000   28.000000   15.741700    0.000000    0.000000
75%      1.000000    3.000000   38.000000   33.500000    1.000000    1.000000
max      1.000000    3.000000   80.000000  512.329200    5.000000    6.000000

In [111]:
#3: Deteksi masalah data
df.isnull().sum()

survived    0
pclass      0
name        0
sex         0
age         0
fare        1
sibsp       0
parch       0
dtype: int64

In [112]:
#4: Imputasi data
# Imputasi hanya kolom numerik
num_cols = df.select_dtypes(include='number').columns

imputer = SimpleImputer(strategy='mean')
df_imputed = df.copy()
df_imputed[num_cols] = imputer.fit_transform(df[num_cols])

# Fit GMM pada kolom fare (yang sudah diimputasi)
gmm = GaussianMixture(n_components=2, max_iter=100, random_state=42)
gmm.fit(df_imputed[['fare']])

# Menampilkan DataFrame hasil imputasi
df_imputed.head()

,survived,pclass,name,sex,age,fare,sibsp,parch
0,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,34.733006,1.0,0.0
1,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.283300,1.0,0.0
2,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,7.925000,0.0,0.0
3,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.100000,1.0,0.0
4,0.0,3.0,"Allen, Mr. William Henry",male,35.0,8.050000,0.0,0.0